% sign_section/2
sign_section(none, all).
sign_section(altered_color, all).
sign_section(altered_color, branches).
sign_section(altered_color, leaves).
sign_section(altered_color, lower_leaves).
sign_section(altered_color, roots).
sign_section(altered_color, upper_leaves).
sign_section(angular_lesions, leaves).
sign_section(black_leathery_spot, fruits).
sign_section(black_sunken_spot, fruits).
sign_section(circular_lesions, leaves).
sign_section(clear_gummy_substance, fruits).
sign_section(clustering_cottony, lower_side_leaves).
sign_section(cotton_like_downy_substance, lower_side_leaves).
sign_section(cutworms_under_debris, all).
sign_section(cutworms_under_leaves, leaves).
sign_section(dead_patches, bark).
sign_section(death_of_growing_point, shoot).
sign_section(death_of_plant_tissue, all).
sign_section(deformed, all).
sign_section(deformed, buds).
sign_section(deformed, leaves).
sign_section(delayed_growth, all).
sign_section(dry, all).
sign_section(dry, leaves).
sign_section(dying, branches).
sign_section(early_fall, leaves).
sign_section(excessive_tillering_growth, all).
sign_section(fail_to_form, buds).
sign_section(flies, leaves).
sign_section(fuzzy_looking_spores, lower_side_leaves).
sign_section(highly_branched_growth, roots).
sign_section(husks, soil).
sign_section(increased_growth, roots).
sign_section(irregular_lesions, leaves).
sign_section(irregular_water_soaked_blotches, fruits).
sign_section(irregular_water_soaked_blotches, lower_leaves).
sign_section(irregular_water_soaked_blotches, stem).
sign_section(large_spots, fruits).
sign_section(mottled, leaves).
sign_section(necrotic_lesions, leaves).
sign_section(parachute_shape, leaves).
sign_section(poor_quality, fruits).
sign_section(poor_quantity, fruits).
sign_section(poor_quantity, leaves).
sign_section(shot_holes, leaves).
sign_section(small_flies, all).
sign_section(small_holes, leaves).
sign_section(small_size, leaves).
sign_section(smell_strange, root).
sign_section(spots_drop_out, leaves).
sign_section(spots, fruits).
sign_section(spots, leaves).
sign_section(spots, stem).
sign_section(spots, upper_side_lower_leaves).
sign_section(sticky_honeydew, all).
sign_section(sticky_webbing, all).
sign_section(streaking, leaves).
sign_section(stunted_growth, all).
sign_section(stunted_growth, leaves).
sign_section(stunted_growth, shoot).
sign_section(stunted_growth, stem).
sign_section(stunted_growth, upper_leaves).
sign_section(thin_size, leaves).
sign_section(visible_spores, leaves).
sign_section(water_soaked_spots, flower).
sign_section(water_soaked_spots, lower_leaves).
sign_section(water_soaked_spots, stem).
sign_section(white_powdery_substance, all).
sign_section(wilting_margins, leaves).
sign_section(withering, all).
sign_section(withering, leaves).

% sign_color/2
sign_color(altered_color, chlorotic).
sign_color(altered_color, dark_green).
sign_color(altered_color, blotchy_chlorosis).
sign_color(altered_color, interveinal_chlorosis).
sign_color(altered_color, chlorotic).
sign_color(altered_color, reddish_purple).
sign_color(altered_color, dark_veins).
sign_color(altered_color, brown_discoloration).
sign_color(altered_color, angular_chlorosis).
sign_color(altered_color, brown).
sign_color(altered_color, rounded_chlorosis).
sign_color(altered_color, bronze).
sign_color(altered_color, yellowish_outline).
sign_color(cotton_like_downy_substance, greysh).
sign_color(cotton_like_downy_substance, white).
sign_color(flies, white).
sign_color(fuzzy_looking_spores, greysh).
sign_color(fuzzy_mold, grey).
sign_color(husks, grey).
sign_color(husks, white).
sign_color(irregular_water_soaked_blotches, greenish_black).
sign_color(irregular_water_soaked_blotches, greenish_black).
sign_color(large_spots, black).
sign_color(leathery_spot, black).
sign_color(small_flies, black).
sign_color(spots, black).
sign_color(spots, black).
sign_color(spots, brown).
sign_color(spots, chlorosis).
sign_color(spots, dark_brown).
sign_color(spots, dark_margin).
sign_color(spots, necrotic).
sign_color(spots, pale_green).
sign_color(spots, purplish).
sign_color(spots, red).
sign_color(spots, reddish).
sign_color(spots, tan).
sign_color(spots, whitish_yellow).
sign_color(spots, yellow).
sign_color(sunken_spot, black).