rule(1,condition(X,nitrogen),[manifests(X,symptom(lower_leaves,altered_color,chlorotic))]).
rule(2,condition(X,nitrogen),[manifests(X,symptom(leaves,early_fall,none))]).
rule(3,condition(X,nitrogen),[manifests(X,symptom(roots,increased_growth,none))]).
rule(4,condition(X,nitrogen),[manifests(X,symptom(shoot,stunted_growth,none))]).
rule(5,condition(X,phosphorus),[manifests(X,symptom(leaves,poor_quantity,none))]).
rule(6,condition(X,phosphorus),[manifests(X,symptom(leaves,altered_color,dark_green))]).
rule(7,condition(X,phosphorus),[manifests(X,symptom(leaves,small_size,none))]).
rule(8,condition(X,phosphorus),[manifests(X,symptom(roots,increased_growth,none))]).
rule(9,condition(X,phosphorus),[manifests(X,symptom(shoot,stunted_growth,none))]).
rule(10,condition(X,potassium),[manifests(X,symptom(lower_leaves,altered_color,blotchy_chlorosis))]).
rule(11,condition(X,potassium),[manifests(X,symptom(leaves,altered_color,interveinal_chlorosis))]).
rule(12,condition(X,potassium),[manifests(X,symptom(upper_leaves,stunted_growth,none))]).
rule(13,condition(X,sulfur),[manifests(X,symptom(upper_leaves,altered_color,chlorotic))]).
rule(14,condition(X,sulfur),[manifests(X,symptom(upper_leaves,stunted_growth,none))]).
rule(15,condition(X,sulfur),[manifests(X,symptom(leaves,thin_size,none))]).
rule(16,condition(X,magnesium),[manifests(X,symptom(lower_leaves,altered_color,interveinal_chlorosis))]).
rule(17,condition(X,magnesium),[manifests(X,symptom(leaves,altered_color,chlorotic))]).
rule(18,condition(X,magnesium),[manifests(X,symptom(leaves,altered_color,reddish_purple))]).
rule(19,condition(X,calcium),[manifests(X,symptom(leaves,deformed,none))]).
rule(20,condition(X,calcium),[manifests(X,symptom(leaves,altered_color,dark_veins))]).
rule(21,condition(X,calcium),[manifests(X,symptom(upper_leaves,spots,brown))]).
rule(22,condition(X,calcium),[manifests(X,symptom(upper_leaves,stunted_growth))]).
rule(23,condition(X,calcium),[manifests(X,symptom(leaves,parachute_shape,none))]).
rule(24,condition(X,calcium),[manifests(X,symptom(all,deformed,none))]).
rule(25,condition(X,boron),[manifests(X,symptom(buds,fail_to_form,none))]).
rule(26,condition(X,boron),[manifests(X,symptom(leaves,irregular_lesions,none))]).
rule(27,condition(X,boron),[manifests(X,symptom(shoot,death_of_growing_point,none))]).
rule(28,condition(X,boron),[manifests(X,symptom(upper_leaves,altered_color,chlorotic))]).
rule(29,condition(X,boron),[manifests(X,symptom(leaves,spots,whitish_yellow))]).
rule(30,condition(X,boron),[manifests(X,symptom(stem,stunted_growth,none))]).
rule(31,condition(X,boron),[manifests(X,symptom(leaves,deformed,none))]).
rule(32,condition(X,boron),[manifests(X,symptom(buds,deformed,none))]).
rule(33,condition(X,chloride),[manifests(X,symptom(leaves,spots,necrotic))]).
rule(34,condition(X,chloride),[manifests(X,symptom(leaves,spots,chlorotic))]).
rule(35,condition(X,chloride),[manifests(X,symptom(leaves,wilting_margins,none))]).
rule(36,condition(X,chloride),[manifests(X,symptom(roots,highly_branched_growth,none))]).
rule(37,condition(X,copper),[manifests(X,symptom(upper_leaves,altered_color,chlorotic))]).
rule(38,condition(X,copper),[manifests(X,symptom(all,altered_color,brown_discoloration))]).
rule(39,condition(X,copper),[manifests(X,symptom(all,stunted_growth,none))]).
rule(40,condition(X,copper),[manifests(X,symptom(all,delayed_growth,none))]).
rule(41,condition(X,copper),[manifests(X,symptom(all,excessive_tillering_growth,none))]).
rule(42,condition(X,iron),[manifests(X,symptom(fruits,poor_quantity,none))]).
rule(43,condition(X,iron),[manifests(X,symptom(fruits,poor_quality,none))]).
rule(44,condition(X,iron),[manifests(X,symptom(upper_leaves,altered_color,angular_chlorosis))]).
rule(45,condition(X,iron),[manifests(X,symptom(roots,altered_color,brown))]).
rule(46,condition(X,iron),[manifests(X,symptom(root,smell_strange,none))]).
rule(47,condition(X,manganese),[manifests(X,symptom(leaves,withering,none)),manifests(X,symptom(leaves,altered_color,brown))]).
rule(48,condition(X,manganese),[manifests(X,symptom(lower_leaves,altered_color,chlorotic))]).
rule(49,condition(X,manganese),[manifests(X,symptom(leaves,altered_color,interveinal_chlorosis))]).
rule(50,condition(X,manganese),[manifests(X,symptom(leaves,spots,brown))]).
rule(51,condition(X,zinc),[manifests(X,symptom(upper_leaves,altered_color,rounded_chlorosis))]).
rule(52,condition(X,zinc),[manifests(X,symptom(leaves,altered_color,bronze))]).
rule(53,condition(X,zinc),[manifests(X,symptom(leaves,stunted_growth,none))]).
rule(54,condition(X,zinc),[manifests(X,symptom(leaves,deformed,none))]).
rule(55,condition(X,black_spot),[manifests(X,symptom(leaves,chlorotic,none)),manifests(X,symptom(leaves,early_fall,none))]).
rule(56,condition(X,black_spot),[manifests(X,symptom(upper_side_leaves,spots,black,none))]).
rule(57,condition(X,leaf_spot),[manifests(X,symptom(leaves,visible_spores,none)),manifests(X,symptom(leaves,spots,brown)),manifests(X,symptom(leaves,spots,dark_margin))]).
rule(58,condition(X,leaf_spot),[manifests(X,symptom(leaves,visible_spores,none)),manifests(X,symptom(leaves,spots,tan)),manifests(X,symptom(leaves,spots,dark_margin))]).
rule(59,condition(X,leaf_spot),[manifests(X,symptom(leaves,visible_spores,none)),manifests(X,symptom(leaves,spots,reddish)),manifests(X,symptom(leaves,spots,dark_margin))]).
rule(60,condition(X,leaf_spot),[manifests(X,symptom(leaves,angular_lesions,none))]).
rule(61,condition(X,leaf_spot),[manifests(X,symptom(leaves,angular_lesions,none)),manifests(X,symptom(leaves,altered_color,yellowish_outline))]).
rule(62,condition(X,leaf_spot),[manifests(X,symptom(leaves,circular_lesions,none))]).
rule(63,condition(X,leaf_spot),[manifests(X,symptom(leaves,circular_lesions,none)),manifests(X,symptom(leaves,altered_color,yellowish_outline))]).
rule(64,condition(X,leaf_spot),[manifests(X,symptom(leaves,necrotic_lesions,none))]).
rule(65,condition(X,leaf_spot),[manifests(X,symptom(leaves,necrotic_lesions,none)),manifests(X,symptom(leaves,altered_color,yellowish_outline))]).
rule(66,condition(X,powdery_mildew),[manifests(X,symptom(all,white_powdery_substance,none))]).
rule(67,condition(X,downy_mildew),[manifests(X,symptom(upper_side_lower_leaves,spots,pale_green))]).
rule(68,condition(X,downy_mildew),[manifests(X,symptom(upper_side_lower_leaves,spots,yellow))]).
rule(69,condition(X,downy_mildew),[manifests(X,symptom(lower_side_leaves,white_cotton_like_downy_substance,none))]).
rule(70,condition(X,downy_mildew),[manifests(X,symptom(lower_side_leaves,greysh_cotton_like_downy_substance,none))]).
rule(71,condition(X,downy_mildew),[manifests(X,symptom(lower_side_leaves,grayish_fuzzy_looking_spores,none))]).
rule(72,condition(X,blight),[manifests(X,symptom(leaves,altered_color,chlorotic))]).
rule(73,condition(X,blight),[manifests(X,symptom(all,spot,none))]).
rule(74,condition(X,blight),[manifests(X,symptom(all,withering,none))]).
rule(75,condition(X,blight),[manifests(X,symptom(all,death_of_plant_tissue,none))]).
rule(76,condition(X,canker),[manifests(X,symptom(leaves,small_holes,none))]).
rule(77,condition(X,canker),[manifests(X,symptom(bark,dead_patches,none))]).
rule(78,condition(X,shot_hole),[manifests(X,symptom(leaves,spots,tan))]).
rule(79,condition(X,shot_hole),[manifests(X,symptom(leaves,spots_drop_out,none))]).
rule(80,condition(X,shot_hole),[manifests(X,symptom(leaves,shot_holes,none))]).
rule(81,condition(X,shot_hole),[manifests(X,symptom(leaves,spots,purplish))]).
rule(82,condition(X,shot_hole),[manifests(X,symptom(fruits,spots,red))]).
rule(83,condition(X,shot_hole),[manifests(X,symptom(fruits,spots,red)),manifests(X,symptom(fruits,clear_gummy_substance,none))]).
rule(84,condition(X,shot_hole),[manifests(X,symptom(fruits,spots,purplish))]).
rule(85,condition(X,shot_hole),[manifests(X,symptom(fruits,spots,purplish)),manifests(X,symptom(fruits,clear_gummy_substance,none))]).
rule(86,condition(X,early_blight),[manifests(X,symptom(leaves,spots,dark_brown))]).
rule(87,condition(X,early_blight),[manifests(X,symptom(leaves,spots,black))]).
rule(88,condition(X,early_blight),[manifests(X,symptom(stem,spots,black))]).
rule(89,condition(X,early_blight),[manifests(X,symptom(fruits,sunken_spot,black))]).
rule(90,condition(X,early_blight),[manifests(X,symptom(fruits,leathery_spot,black))]).
rule(91,condition(X,early_blight),[manifests(X,symptom(fruits,large_spots,black))]).
rule(92,condition(X,late_blight),[manifests(X,symptom(lower_leaves,irregular_water_soaked_blotches,greenish_black))]).
rule(93,condition(X,late_blight),[manifests(X,symptom(stem,irregular_water_soaked_blotches,greenish_black))]).
rule(94,condition(X,late_blight),[manifests(X,symptom(lower_leaves,irregular_water_soaked_blotches,greenish_black)),manifests(X,symptom(fruits,irregular_water_soaked_blotches,greenish_black))]).
rule(95,condition(X,late_blight),[manifests(X,symptom(stem,irregular_water_soaked_blotches,greenish_black)),manifests(X,symptom(fruits,irregular_water_soaked_blotches,greenish_black))]).
rule(96,condition(X,grey_mold),[manifests(X,symptom(all,fuzzy_mold,grey))]).
rule(97,condition(X,grey_mold),[manifests(X,symptom(stem,water_soaked_spots,none))]).
rule(98,condition(X,grey_mold),[manifests(X,symptom(flower,water_soaked_spots,none))]).
rule(99,condition(X,grey_mold),[manifests(X,symptom(lower_leaves,water_soaked_spots,none))]).
rule(100,condition(X,verticilium_wilt),[manifests(X,symptom(branches,altered_color,chlorotic))]).
rule(101,condition(X,verticilium_wilt),[manifests(X,symptom(branches,wilting,none))]).
rule(102,condition(X,verticilium_wilt),[manifests(X,symptom(branches,dying,none))]).
rule(103,condition(X,apthids),[manifests(X,symptom(all,sticky_honeydew,none))]).
rule(104,condition(X,apthids),[manifests(X,symptom(all,deformed,none))]).
rule(105,condition(X,apthids),[manifests(X,symptom(soil,husks,white))]).
rule(106,condition(X,apthids),[manifests(X,symptom(soil,husks,grey))]).
rule(107,condition(X,apthids),[manifests(X,symptom(leaves,random_chlorosis,none))]).
rule(108,condition(X,thrips),[manifests(X,symptom(leaves,mottled,none))]).
rule(109,condition(X,thrips),[manifests(X,symptom(leaves,streaking,none))]).
rule(110,condition(X,thrips),[manifests(X,symptom(leaves,altered_color,brown))]).
rule(111,condition(X,spider_mites),[manifests(X,symptom(all,sticky_webbing,none))]).
rule(112,condition(X,spider_mites),[manifests(X,symptom(leaves,mottled,none)),manifests(X,symptom(leaves,spots,brown))]).
rule(113,condition(X,scale_insects),[manifests(X,symptom(all,sticky_honeydew,none))]).
rule(114,condition(X,white_flies),[manifests(X,symptom(leaves,flies,white)),manifests(X,symptom(leaves,altered_color,chlorotic))]).
rule(115,condition(X,white_flies),[manifests(X,symptom(leaves,flies,white)),manifests(X,symptom(leaves,dry))]).
rule(116,condition(X,cutworms),[manifests(X,symptom(leaves,cutworms_under_leaves,none))]).
rule(117,condition(X,cutworms),[manifests(X,symptom(all,cutworms_under_debris,none))]).
rule(118,condition(X,fungus_gnats),[manifests(X,symptom(all,small_flies,black))]).
rule(119,condition(X,mealy_bugs),[manifests(X,symptom(all,stunted_growth,none))]).
rule(120,condition(X,mealy_bugs),[manifests(X,symptom(all,withering,none))]).
rule(121,condition(X,mealy_bugs),[manifests(X,symptom(leaves,altered_color,chlorotic))]).
rule(122,condition(X,mealy_bugs),[manifests(X,symptom(lower_side_leaves,clustering_cottony,none))]).
rule(123,condition(X,mealy_bugs),[manifests(X,symptom(leaves,altered_color,chlorotic)),manifests(X,symptom(leaves,early_fall,none))]).
rule(124,condition(X,mealy_bugs),[manifests(X,symptom(all,dry,none))]).
rule(125,condition(X,mealy_bugs),[manifests(X,symptom(all,sticky_honeydew,none))]).
rule(126,problem(X,wet),[reading(X,humidity,high)]).
rule(127,problem(X,dry),[reading(X,humidity,low)]).
rule(128,problem(X,hot),[reading(X,temperature,high)]).
rule(129,problem(X,cold),[reading(X,temperature,low)]).
rule(130,problem(X,infestation),[condition(X,apthids)]).
rule(131,problem(X,infestation),[condition(X,thrips)]).
rule(132,problem(X,infestation),[condition(X,spider_mites)]).
rule(133,problem(X,infestation),[condition(X,scale_insects)]).
rule(134,problem(X,infestation),[condition(X,white_flies)]).
rule(135,problem(X,infestation),[condition(X,cutworms)]).
rule(136,problem(X,infestation),[condition(X,fungus_gnats)]).
rule(137,problem(X,infestation),[condition(X,mealy_bugs)]).
rule(138,problem(X,disease),[condition(X,black_spot)]).
rule(139,problem(X,disease),[condition(X,leaf_spot)]).
rule(140,problem(X,disease),[condition(X,powdery_mildew)]).
rule(141,problem(X,disease),[condition(X,downy_mildew)]).
rule(142,problem(X,disease),[condition(X,blight)]).
rule(143,problem(X,disease),[condition(X,canker)]).
rule(144,problem(X,disease),[condition(X,shot_hole)]).
rule(145,problem(X,disease),[condition(X,early_blight)]).
rule(146,problem(X,disease),[condition(X,late_blight)]).
rule(147,problem(X,disease),[condition(X,grey_mold)]).
rule(148,problem(X,disease),[condition(X,verticilium_wilt)]).
rule(149,problem(X,nutrient_deficiency),[condition(X,nitrogen)]).
rule(150,problem(X,nutrient_deficiency),[condition(X,phosphorus)]).
rule(151,problem(X,nutrient_deficiency),[condition(X,potassium)]).
rule(152,problem(X,nutrient_deficiency),[condition(X,sulfur)]).
rule(153,problem(X,nutrient_deficiency),[condition(X,magnesium)]).
rule(154,problem(X,nutrient_deficiency),[condition(X,calcium)]).
rule(155,problem(X,nutrient_deficiency),[condition(X,boron)]).
rule(156,problem(X,nutrient_deficiency),[condition(X,chloride)]).
rule(157,problem(X,nutrient_deficiency),[condition(X,copper)]).
rule(158,problem(X,nutrient_deficiency),[condition(X,iron)]).
rule(159,problem(X,nutrient_deficiency),[condition(X,manganese)]).
rule(160,problem(X,nutrient_deficiency),[condition(X,zinc)]).
rule(161,health_issue(X,abiotic),[problem(X,wet)]).
rule(162,health_issue(X,abiotic),[problem(X,dry)]).
rule(163,health_issue(X,abiotic),[problem(X,hot)]).
rule(164,health_issue(X,abiotic),[problem(X,cold)]).
rule(165,health_issue(X,abiotic),[problem(X,nutrient_deficiency)]).
rule(166,health_issue(X,pests),[problem(X,infestation)]).
rule(167,health_issue(X,biotic),[problem(X,disease)]).