% sign_location/2
sign_location(none,all).
sign_location(altered_color,all).
sign_location(altered_color,branches).
sign_location(altered_color,leaves).
sign_location(altered_color,lower_leaves).
sign_location(altered_color,roots).
sign_location(altered_color,upper_leaves).
sign_location(angular_lesions,leaves).
sign_location(black_leathery_spot,fruits).
sign_location(black_sunken_spot,fruits).
sign_location(circular_lesions,leaves).
sign_location(clear_gummy_substance,fruits).
sign_location(clustering_cottony,lower_side_leaves).
sign_location(cotton_like_downy_substance,lower_side_leaves).
sign_location(cutworms_under_debris,all).
sign_location(cutworms_under_leaves,leaves).
sign_location(dead_patches,bark).
sign_location(death_of_growing_point,shoot).
sign_location(death_of_plant_tissue,all).
sign_location(deformed,all).
sign_location(deformed,buds).
sign_location(deformed,leaves).
sign_location(delayed_growth,all).
sign_location(dry,all).
sign_location(dry,leaves).
sign_location(dying,branches).
sign_location(early_fall,leaves).
sign_location(excessive_tillering_growth,all).
sign_location(fail_to_form,buds).
sign_location(flies,leaves).
sign_location(fuzzy_looking_spores,lower_side_leaves).
sign_location(highly_branched_growth,roots).
sign_location(husks,soil).
sign_location(increased_growth,roots).
sign_location(irregular_lesions,leaves).
sign_location(irregular_water_soaked_blotches,fruits).
sign_location(irregular_water_soaked_blotches,lower_leaves).
sign_location(irregular_water_soaked_blotches,stem).
sign_location(large_spots,fruits).
sign_location(mottled,leaves).
sign_location(necrotic_lesions,leaves).
sign_location(parachute_shape,leaves).
sign_location(poor_quality,fruits).
sign_location(poor_quantity,fruits).
sign_location(poor_quantity,leaves).
sign_location(shot_holes,leaves).
sign_location(small_flies,all).
sign_location(small_holes,leaves).
sign_location(small_size,leaves).
sign_location(smell_strange,root).
sign_location(spots_drop_out,leaves).
sign_location(spots,fruits).
sign_location(spots,leaves).
sign_location(spots,stem).
sign_location(spots,upper_side_lower_leaves).
sign_location(sticky_honeydew,all).
sign_location(sticky_webbing,all).
sign_location(streaking,leaves).
sign_location(stunted_growth,all).
sign_location(stunted_growth,leaves).
sign_location(stunted_growth,shoot).
sign_location(stunted_growth,stem).
sign_location(stunted_growth,upper_leaves).
sign_location(thin_size,leaves).
sign_location(visible_spores,leaves).
sign_location(water_soaked_spots,flower).
sign_location(water_soaked_spots,lower_leaves).
sign_location(water_soaked_spots,stem).
sign_location(white_powdery_substance,all).
sign_location(wilting_margins,leaves).
sign_location(withering,all).
sign_location(withering,leaves).

% sign_color/2
sign_color(altered_color,chlorotic).
sign_color(altered_color,dark_green).
sign_color(altered_color,blotchy_chlorosis).
sign_color(altered_color,interveinal_chlorosis).
sign_color(altered_color,chlorotic).
sign_color(altered_color,reddish_purple).
sign_color(altered_color,dark_veins).
sign_color(altered_color,brown_discoloration).
sign_color(altered_color,angular_chlorosis).
sign_color(altered_color,brown).
sign_color(altered_color,rounded_chlorosis).
sign_color(altered_color,bronze).
sign_color(altered_color,yellowish_outline).
sign_color(cotton_like_downy_substance,greysh).
sign_color(cotton_like_downy_substance,white).
sign_color(flies,white).
sign_color(fuzzy_looking_spores,greysh).
sign_color(fuzzy_mold,grey).
sign_color(husks,grey).
sign_color(husks,white).
sign_color(irregular_water_soaked_blotches,greenish_black).
sign_color(irregular_water_soaked_blotches,greenish_black).
sign_color(large_spots,black).
sign_color(leathery_spot,black).
sign_color(small_flies,black).
sign_color(spots,black).
sign_color(spots,black).
sign_color(spots,brown).
sign_color(spots,chlorosis).
sign_color(spots,dark_brown).
sign_color(spots,dark_margin).
sign_color(spots,necrotic).
sign_color(spots,pale_green).
sign_color(spots,purplish).
sign_color(spots,red).
sign_color(spots,reddish).
sign_color(spots,tan).
sign_color(spots,whitish_yellow).
sign_color(spots,yellow).
sign_color(sunken_spot,black).