manifests(X,symptom(upper_leaves,stunted_growth)).
manifests(X,symptom(all,altered_color,brown_discoloration)).
manifests(X,symptom(all,cutworms_under_debris,none)).
manifests(X,symptom(all,death_of_plant_tissue,none)).
manifests(X,symptom(all,deformed,none)).
manifests(X,symptom(all,delayed_growth,none)).
manifests(X,symptom(all,dry,none)).
manifests(X,symptom(all,excessive_tillering_growth,none)).
manifests(X,symptom(all,fuzzy_mold,grey)).
manifests(X,symptom(all,small_flies,black)).
manifests(X,symptom(all,spot,none)).
manifests(X,symptom(all,sticky_honeydew,none)).
manifests(X,symptom(all,sticky_webbing,none)).
manifests(X,symptom(all,stunted_growth,none)).
manifests(X,symptom(all,white_powdery_substance,none)).
manifests(X,symptom(all,withering,none)).
manifests(X,symptom(bark,dead_patches,none)).
manifests(X,symptom(branches,altered_color,chlorotic)).
manifests(X,symptom(branches,dying,none)).
manifests(X,symptom(branches,wilting,none)).
manifests(X,symptom(buds,deformed,none)).
manifests(X,symptom(buds,fail_to_form,none)).
manifests(X,symptom(flower,water_soaked_spots,none)).
manifests(X,symptom(fruits,large_spots,black)).
manifests(X,symptom(fruits,leathery_spot,black)).
manifests(X,symptom(fruits,poor_quality,none)).
manifests(X,symptom(fruits,poor_quantity,none)).
manifests(X,symptom(fruits,spots,purplish)).
manifests(X,symptom(fruits,spots,red)).
manifests(X,symptom(fruits,sunken_spot,black)).
manifests(X,symptom(leaves,altered_color,bronze)).
manifests(X,symptom(leaves,altered_color,brown)).
manifests(X,symptom(leaves,altered_color,chlorotic)).
manifests(X,symptom(leaves,altered_color,dark_green)).
manifests(X,symptom(leaves,altered_color,dark_veins)).
manifests(X,symptom(leaves,altered_color,interveinal_chlorosis)).
manifests(X,symptom(leaves,altered_color,reddish_purple)).
manifests(X,symptom(leaves,angular_lesions,none)).
manifests(X,symptom(leaves,circular_lesions,none)).
manifests(X,symptom(leaves,cutworms_under_leaves,none)).
manifests(X,symptom(leaves,deformed,none)).
manifests(X,symptom(leaves,early_fall,none)).
manifests(X,symptom(leaves,irregular_lesions,none)).
manifests(X,symptom(leaves,mottled,none)).
manifests(X,symptom(leaves,necrotic_lesions,none)).
manifests(X,symptom(leaves,parachute_shape,none)).
manifests(X,symptom(leaves,poor_quantity,none)).
manifests(X,symptom(leaves,random_chlorosis,none)).
manifests(X,symptom(leaves,shot_holes,none)).
manifests(X,symptom(leaves,small_holes,none)).
manifests(X,symptom(leaves,small_size,none)).
manifests(X,symptom(leaves,spots,black)).
manifests(X,symptom(leaves,spots,brown)).
manifests(X,symptom(leaves,spots,chlorotic)).
manifests(X,symptom(leaves,spots,dark_brown)).
manifests(X,symptom(leaves,spots,necrotic)).
manifests(X,symptom(leaves,spots,purplish)).
manifests(X,symptom(leaves,spots,tan)).
manifests(X,symptom(leaves,spots,whitish_yellow)).
manifests(X,symptom(leaves,spots_drop_out,none)).
manifests(X,symptom(leaves,streaking,none)).
manifests(X,symptom(leaves,stunted_growth,none)).
manifests(X,symptom(leaves,thin_size,none)).
manifests(X,symptom(leaves,wilting_margins,none)).
manifests(X,symptom(lower_leaves,altered_color,blotchy_chlorosis)).
manifests(X,symptom(lower_leaves,altered_color,chlorotic)).
manifests(X,symptom(lower_leaves,altered_color,interveinal_chlorosis)).
manifests(X,symptom(lower_leaves,irregular_water_soaked_blotches,greenish_black)).
manifests(X,symptom(lower_leaves,water_soaked_spots,none)).
manifests(X,symptom(lower_side_leaves,clustering_cottony,none)).
manifests(X,symptom(lower_side_leaves,grayish_fuzzy_looking_spores,none)).
manifests(X,symptom(lower_side_leaves,greysh_cotton_like_downy_substance,none)).
manifests(X,symptom(lower_side_leaves,white_cotton_like_downy_substance,none)).
manifests(X,symptom(root,smell_strange,none)).
manifests(X,symptom(roots,altered_color,brown)).
manifests(X,symptom(roots,highly_branched_growth,none)).
manifests(X,symptom(roots,increased_growth,none)).
manifests(X,symptom(shoot,death_of_growing_point,none)).
manifests(X,symptom(shoot,stunted_growth,none)).
manifests(X,symptom(soil,husks,grey)).
manifests(X,symptom(soil,husks,white)).
manifests(X,symptom(stem,irregular_water_soaked_blotches,greenish_black)).
manifests(X,symptom(stem,spots,black)).
manifests(X,symptom(stem,stunted_growth,none)).
manifests(X,symptom(stem,water_soaked_spots,none)).
manifests(X,symptom(upper_leaves,altered_color,angular_chlorosis)).
manifests(X,symptom(upper_leaves,altered_color,chlorotic)).
manifests(X,symptom(upper_leaves,altered_color,rounded_chlorosis)).
manifests(X,symptom(upper_leaves,spots,brown)).
manifests(X,symptom(upper_leaves,stunted_growth,none)).
manifests(X,symptom(upper_side_lower_leaves,spots,pale_green)).
manifests(X,symptom(upper_side_lower_leaves,spots,yellow)).
manifests(X,symptom(upper_side_leaves,spots,black,none)).