symptom(upper_leaves,stunted_growth).
symptom(all,altered_color,brown_discoloration).
symptom(all,cutworms_under_debris,none).
symptom(all,death_of_plant_tissue,none).
symptom(all,deformed,none).
symptom(all,delayed_growth,none).
symptom(all,dry,none).
symptom(all,excessive_tillering_growth,none).
symptom(all,fuzzy_mold,grey).
symptom(all,small_flies,black).
symptom(all,spot,none).
symptom(all,sticky_honeydew,none).
symptom(all,sticky_webbing,none).
symptom(all,stunted_growth,none).
symptom(all,white_powdery_substance,none).
symptom(all,withering,none).
symptom(bark,dead_patches,none).
symptom(branches,altered_color,chlorotic).
symptom(branches,dying,none).
symptom(branches,wilting,none).
symptom(buds,deformed,none).
symptom(buds,fail_to_form,none).
symptom(flower,water_soaked_spots,none).
symptom(fruits,large_spots,black).
symptom(fruits,leathery_spot,black).
symptom(fruits,poor_quality,none).
symptom(fruits,poor_quantity,none).
symptom(fruits,spots,purplish).
symptom(fruits,spots,red).
symptom(fruits,sunken_spot,black).
symptom(leaves,altered_color,bronze).
symptom(leaves,altered_color,brown).
symptom(leaves,altered_color,chlorotic).
symptom(leaves,altered_color,dark_green).
symptom(leaves,altered_color,dark_veins).
symptom(leaves,altered_color,interveinal_chlorosis).
symptom(leaves,altered_color,reddish_purple).
symptom(leaves,angular_lesions,none).
symptom(leaves,circular_lesions,none).
symptom(leaves,cutworms_under_leaves,none).
symptom(leaves,deformed,none).
symptom(leaves,early_fall,none).
symptom(leaves,irregular_lesions,none).
symptom(leaves,mottled,none).
symptom(leaves,necrotic_lesions,none).
symptom(leaves,parachute_shape,none).
symptom(leaves,poor_quantity,none).
symptom(leaves,random_chlorosis,none).
symptom(leaves,shot_holes,none).
symptom(leaves,small_holes,none).
symptom(leaves,small_size,none).
symptom(leaves,spots,black).
symptom(leaves,spots,brown).
symptom(leaves,spots,chlorotic).
symptom(leaves,spots,dark_brown).
symptom(leaves,spots,necrotic).
symptom(leaves,spots,purplish).
symptom(leaves,spots,tan).
symptom(leaves,spots,whitish_yellow).
symptom(leaves,spots_drop_out,none).
symptom(leaves,streaking,none).
symptom(leaves,stunted_growth,none).
symptom(leaves,thin_size,none).
symptom(leaves,wilting_margins,none).
symptom(lower_leaves,altered_color,blotchy_chlorosis).
symptom(lower_leaves,altered_color,chlorotic).
symptom(lower_leaves,altered_color,interveinal_chlorosis).
symptom(lower_leaves,irregular_water_soaked_blotches,greenish_black).
symptom(lower_leaves,water_soaked_spots,none).
symptom(lower_side_leaves,clustering_cottony,none).
symptom(lower_side_leaves,grayish_fuzzy_looking_spores,none).
symptom(lower_side_leaves,greysh_cotton_like_downy_substance,none).
symptom(lower_side_leaves,white_cotton_like_downy_substance,none).
symptom(root,smell_strange,none).
symptom(roots,altered_color,brown).
symptom(roots,highly_branched_growth,none).
symptom(roots,increased_growth,none).
symptom(shoot,death_of_growing_point,none).
symptom(shoot,stunted_growth,none).
symptom(soil,husks,grey).
symptom(soil,husks,white).
symptom(stem,irregular_water_soaked_blotches,greenish_black).
symptom(stem,spots,black).
symptom(stem,stunted_growth,none).
symptom(stem,water_soaked_spots,none).
symptom(upper_leaves,altered_color,angular_chlorosis).
symptom(upper_leaves,altered_color,chlorotic).
symptom(upper_leaves,altered_color,rounded_chlorosis).
symptom(upper_leaves,spots,brown).
symptom(upper_leaves,stunted_growth,none).
symptom(upper_side_lower_leaves,spots,pale_green).
symptom(upper_side_lower_leaves,spots,yellow).
symptom(upper_side_leaves,spots,black,none).